##
# This CI/CD configuration provides a pipeline for
# * building a Docker image (using Dockerfile),
# * storing the image in the container registry,
# * trigger downstream CI/CD pipeline for deployment
#
# In order to build your Docker image, you've to provide a Dockerfile in the
# root of your project, or you can specify a location by setting the DOCKERFILE_PATH
# environment variable.
#
stages:
  - build
  - deploy
 
workflow:
  rules:
    - exists:
        - Dockerfile
    - if: '$DOCKERFILE_PATH'

include:
  # Kaniko Build (expirmental): Enables docker builds without use of privileged mode
  # https://gitlab.kuleuven.be/gitlab/gitlab-ci/-/blob/master/templates/Jobs/Build-Kaniko.gitlab-ci.yml
  - project: gitlab/gitlab-ci
    file: /templates/Jobs/Build-Kaniko.gitlab-ci.yml

deploy:
  stage: deploy
  variables:
    #CI_DEPLOY_REGISTRY: $CI_REGISTRY
    #CI_DEPLOY_REPOSITORY: $CI_PROJECT_PATH
    CI_DEPLOY_TAG: $CI_COMMIT_TAG
  trigger:
    project: mech-cloud/bmcte/skeletal-cell-atlas
    strategy: depend
  rules:
    - if: '$CI_DEPLOY_DISABLED'
      when: never
    - if: $CI_COMMIT_TAG
